apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "false"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$3
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.api.minReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: llm
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      containers:
      - name: {{ .Values.api.containerName }}
        image: {{ .Values.api.containerPath }}:{{ .Values.api.containerLabel }}
        args: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5002",  "--workers", "2"]
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.api.port }}
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "4"  
            memory: "4Gi"
